import type { Startup } from "./types"

export const dummyStartups: Startup[] = [
  {
    id: "1",
    name: "TechFlow AI",
    sector: "Artificial Intelligence",
    stage: "Series A",
    country: "United States",
    description: "AI-powered workflow automation platform for enterprise teams",
    team: "CEO: Sarah Chen (ex-Google), CTO: Michael Park (ex-Meta), 15 engineers",
    metrics: "ARR: $2.5M, Growth: 300% YoY, Customers: 45 enterprise clients",
    score: 92,
    rank: 1,
    feedback: [],
    pipelineStage: "Due Diligence",
    aiScores: {
      llm: 94,
      ml: 91,
      sentiment: 90,
      llmAnalysis:
        "The LLM analysis indicates exceptional market positioning with strong product-market fit. The company demonstrates clear differentiation through its AI-powered automation capabilities, addressing a significant pain point in enterprise workflows. The founding team's background at leading tech companies provides credibility and deep technical expertise.",
      mlAnalysis:
        "Machine learning models predict high success probability based on growth metrics, team composition, and market dynamics. The 300% YoY growth rate significantly exceeds industry benchmarks. Customer retention data and expansion revenue patterns suggest strong product stickiness and increasing customer lifetime value.",
      sentimentAnalysis:
        "Market sentiment analysis shows overwhelmingly positive signals from industry analysts, early customers, and technology media. The company is frequently mentioned in discussions about the future of enterprise automation. Customer testimonials highlight significant productivity gains and ROI, with an average satisfaction score of 4.8/5.",
    },
    rationale: {
      whyInvest: [
        "Strong founding team with FAANG experience",
        "Exceptional 300% YoY growth rate",
        "Large addressable market in enterprise automation",
        "High customer retention and expansion revenue",
      ],
      whyNot: ["Competitive market with established players", "Relatively early stage with execution risk"],
    },
    detailedMetrics: {
      arr: "$2.5M",
      growth: "300%",
      teamSize: 15,
      fundingStage: "Series A",
    },
    companyInfo: {
      founded: "2021",
      headquarters: "San Francisco, CA",
      website: "https://techflowai.com",
      linkedin: "https://linkedin.com/company/techflowai",
      employeeCount: 28,
      fundingRaised: "$8.5M",
    },
  },
  {
    id: "2",
    name: "HealthSync",
    sector: "Healthcare",
    stage: "Seed",
    country: "United States",
    description: "Patient data synchronization platform for healthcare providers",
    team: "CEO: Dr. James Wilson (MD, Stanford), CTO: Lisa Zhang, 8 team members",
    metrics: "ARR: $800K, Growth: 250% YoY, Customers: 120 clinics",
    score: 88,
    rank: 2,
    feedback: [],
    pipelineStage: "Partner Review",
    aiScores: {
      llm: 89,
      ml: 87,
      sentiment: 88,
      llmAnalysis:
        "Healthcare interoperability remains a critical challenge, and HealthSync addresses this with a well-designed solution. The CEO's medical background provides unique domain expertise that competitors lack. The platform's HIPAA compliance and security features are robust, meeting stringent healthcare requirements.",
      mlAnalysis:
        "Predictive models show strong growth trajectory with 120 clinics already onboarded. The healthcare vertical typically has high switching costs, suggesting strong customer retention. Revenue per clinic is growing steadily, indicating successful upselling and feature adoption.",
      sentimentAnalysis:
        "Healthcare providers express high satisfaction with the platform's ease of use and integration capabilities. Industry publications have featured HealthSync as an emerging leader in healthcare data management. Regulatory compliance and data security receive consistently positive feedback from users.",
    },
    rationale: {
      whyInvest: [
        "Healthcare is a massive, growing market",
        "Strong product-market fit with 120 clinics",
        "CEO has deep domain expertise as MD",
        "Impressive growth trajectory at 250% YoY",
      ],
      whyNot: ["Healthcare sales cycles can be long", "Regulatory compliance adds complexity"],
    },
    detailedMetrics: {
      arr: "$800K",
      growth: "250%",
      teamSize: 8,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Boston, MA",
      website: "https://healthsync.io",
      linkedin: "https://linkedin.com/company/healthsync",
      employeeCount: 15,
      fundingRaised: "$3.2M",
    },
  },
  {
    id: "3",
    name: "GreenEnergy Solutions",
    sector: "Clean Energy",
    stage: "Series B",
    country: "Germany",
    description: "Smart grid optimization software for renewable energy distribution",
    team: "CEO: Robert Green (ex-Tesla), 25 employees across engineering and sales",
    metrics: "ARR: $5M, Growth: 180% YoY, Customers: 30 utility companies",
    score: 85,
    rank: 3,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 86,
      ml: 84,
      sentiment: 85,
    },
    rationale: {
      whyInvest: [
        "Clean energy is a high-priority sector globally",
        "Strong revenue at $5M ARR",
        "Ex-Tesla CEO brings valuable experience",
        "Utility companies provide stable, recurring revenue",
      ],
      whyNot: ["Capital-intensive industry", "Dependent on government energy policies"],
    },
    detailedMetrics: {
      arr: "$5M",
      growth: "180%",
      teamSize: 25,
      fundingStage: "Series B",
    },
  },
  {
    id: "4",
    name: "EduTech Pro",
    sector: "Education Technology",
    stage: "Series A",
    country: "United Kingdom",
    description: "Adaptive learning platform with AI-powered personalization",
    team: "CEO: Maria Rodriguez (ex-Coursera), 20 team members",
    metrics: "ARR: $1.8M, Growth: 220% YoY, Users: 50K students",
    score: 82,
    rank: 4,
    feedback: [],
    pipelineStage: "Intro Sent",
    aiScores: {
      llm: 83,
      ml: 81,
      sentiment: 82,
    },
    rationale: {
      whyInvest: [
        "EdTech market continues to expand post-pandemic",
        "Strong user base of 50K students",
        "CEO has proven track record at Coursera",
        "AI personalization is a key differentiator",
      ],
      whyNot: ["Education budgets can be constrained", "High customer acquisition costs"],
    },
    detailedMetrics: {
      arr: "$1.8M",
      growth: "220%",
      teamSize: 20,
      fundingStage: "Series A",
    },
  },
  {
    id: "5",
    name: "FinanceHub",
    sector: "Fintech",
    stage: "Seed",
    country: "Singapore",
    description: "B2B payment processing with embedded finance solutions",
    team: "CEO: David Kim (ex-Stripe), CTO: Anna Lee, 12 engineers",
    metrics: "ARR: $1.2M, Growth: 280% YoY, Transaction volume: $50M",
    score: 79,
    rank: 5,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 80,
      ml: 78,
      sentiment: 79,
      llmAnalysis:
        "FinanceHub demonstrates strong understanding of B2B payment flows and embedded finance opportunities. The CEO's experience at Stripe provides valuable insights into payment infrastructure and go-to-market strategies. The platform's API-first approach enables rapid integration for customers.",
      mlAnalysis:
        "Growth metrics show consistent month-over-month improvement with $50M in transaction volume processed. The take rate and unit economics are healthy, with clear path to profitability. Customer acquisition costs are declining as the product gains market traction and word-of-mouth referrals increase.",
      sentimentAnalysis:
        "Early customers praise the platform's developer-friendly API and comprehensive documentation. The fintech community views FinanceHub as a promising player in the embedded finance space. Social media sentiment and online reviews are predominantly positive, with users highlighting ease of integration and reliable service.",
    },
    rationale: {
      whyInvest: [
        "Fintech is a high-growth sector",
        "Ex-Stripe CEO understands payments deeply",
        "Strong transaction volume of $50M",
        "Embedded finance is a growing trend",
      ],
      whyNot: ["Highly competitive fintech landscape", "Regulatory challenges in multiple markets"],
      keyStrengths:
        "FinanceHub demonstrates exceptional product-market fit with 280% YoY growth and $50M in transaction volume. The founding team's deep payments expertise from Stripe and PayPal provides a significant competitive advantage. The API-first architecture enables rapid customer integration, with an average time-to-first-transaction of just 14 days. Strong unit economics (LTV:CAC of 4:1, 75% gross margin) and high customer retention (95%) indicate a sustainable, scalable business model. The embedded finance offering differentiates FinanceHub from traditional payment processors and creates additional revenue streams.",
      areasOfConcern:
        "The fintech payments space is highly competitive with well-funded incumbents like Stripe, PayPal, and Adyen. Regulatory compliance across multiple jurisdictions adds complexity and cost as the company expands internationally. The current burn rate of $180K/month with 18 months of runway means the company will need to raise additional capital soon. Customer concentration risk exists if a few large customers represent significant revenue. The company's success depends on continued adoption of embedded finance, which is still an emerging trend.",
    },
    detailedMetrics: {
      arr: "$1.2M",
      growth: "280%",
      teamSize: 12,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Singapore",
      website: "https://financehub.sg",
      linkedin: "https://linkedin.com/company/financehub",
      employeeCount: 18,
      fundingRaised: "$4.5M",
      founders: "David Kim (CEO, ex-Stripe), Anna Lee (CTO, ex-PayPal)",
      contactInfo: "contact@financehub.sg",
      location: "Singapore",
      area: "Southeast Asia",
      ventureCapitalFirm: "Sequoia Capital Southeast Asia, Y Combinator",
    },
    marketInfo: {
      industry: "Financial Technology",
      subIndustry: "B2B Payments & Embedded Finance",
      marketSize: "$2.1T global B2B payments market",
      segment: "SMB and Mid-Market B2B Commerce",
      targetPersona: "CFOs and Finance Teams at B2B companies",
      customerProfile: "B2B companies with $5M-$100M revenue processing recurring payments",
      aiDisruptionPropensity: "Medium - AI can optimize fraud detection and underwriting",
      marketFragmentation: "Highly fragmented with regional players and legacy systems",
      b2bOrB2c: "B2B",
      marketCompetitionAnalysis:
        "The B2B payments market is valued at $2.1T globally and growing at 15% CAGR, driven by digitization of business payments and demand for embedded finance solutions. The market is highly fragmented with regional players and legacy systems, creating opportunities for modern API-first platforms. Key competitors include Stripe (dominant in online payments), Bill.com (focused on AP/AR), and regional players like Razorpay (India) and Airwallex (Asia-Pacific). FinanceHub differentiates through its embedded finance offering, allowing B2B platforms to offer financing to their buyers. The competitive moat strengthens with network effects as more buyers and sellers transact on the platform. Regulatory barriers to entry are high, favoring established players with compliance infrastructure.",
    },
    productInfo: {
      productName: "FinanceHub Platform",
      problemSolved:
        "Complex B2B payment processing with poor integration, high fees, and limited financing options for buyers",
      painIntensity: "High - Payment delays and financing gaps directly impact cash flow and growth",
      productStatus: "Live in production with 85+ active customers",
      horizontalOrVertical: "Horizontal - Applicable across B2B industries",
      stackPosition: "Infrastructure layer - Payment processing and embedded finance",
      uniqueFeatures:
        "API-first architecture, embedded financing options, multi-currency support, automated reconciliation",
      adoption: "Strong adoption with 280% YoY growth and $50M transaction volume",
      valueProp: "Reduce payment processing costs by 40%, accelerate cash collection by 15 days, offer buyer financing",
      moat: "Network effects from buyer-seller connections, proprietary underwriting data, integration partnerships",
    },
    businessModelInfo: {
      modelType: "B2B SaaS + Transaction Fees",
      revenueModel: "Platform fee (0.5-1.5% of transaction value) + monthly subscription ($500-$5K)",
      pricingStrategy: "Tiered pricing based on transaction volume with enterprise custom pricing",
      unitEconomics: "LTV:CAC ratio of 4:1, payback period of 8 months, gross margin 75%",
      capitalIntensity: "Low - Software-based with minimal infrastructure costs",
    },
    salesInfo: {
      salesMotion: "Product-led growth with sales-assisted conversion for enterprise",
      salesCycleLength: "30-60 days for SMB, 90-120 days for enterprise",
      numberOfCustomers: "85 active customers",
      customerValidation: "Strong - 95% customer retention, NPS of 68",
      gtmStrategy: "Developer-first approach with API documentation, partnerships with accounting software",
      channels: "Direct sales, partner referrals, developer community, content marketing",
      salesComplexity: "Medium - Requires technical integration and finance team buy-in",
      adoptionRate: "Fast - Average time to first transaction is 14 days",
    },
    teamInfo: {
      teamDepth: "Strong technical team with 12 engineers, 3 in sales, 2 in operations, 1 in finance",
      keyTeamMembers:
        "David Kim (CEO, 8 years at Stripe), Anna Lee (CTO, 6 years at PayPal), Sarah Tan (Head of Sales, ex-Square)",
      boardMembers: "David Kim (CEO), Anna Lee (CTO), Michael Chen (Investor, Sequoia), Lisa Wong (Independent)",
      advisors: "Patrick Collison (Stripe Co-founder), John Doerr (Kleiner Perkins), Amy Chang (ex-Google Payments)",
      foundersEducation: "David Kim: Stanford CS, MBA from Harvard; Anna Lee: MIT CS, MS from Carnegie Mellon",
      foundersPriorExperience:
        "David Kim: 8 years at Stripe (Payments Infrastructure Lead), 2 years at Square. Anna Lee: 6 years at PayPal (Engineering Manager), 3 years at Braintree",
      teamExecutionAssessment:
        "The founding team demonstrates exceptional execution capability with complementary skills. David Kim's 8 years at Stripe provides deep expertise in payment infrastructure, regulatory compliance, and scaling fintech products. Anna Lee's 6 years at PayPal brings strong technical leadership and experience building reliable payment systems. The team has successfully launched the product, onboarded 85 customers, and achieved $50M in transaction volume within 18 months - demonstrating strong product-market fit and execution velocity. The advisory board includes Patrick Collison (Stripe co-founder), providing strategic guidance and credibility. Key execution risks include the need to scale the team while maintaining product quality, and managing regulatory compliance as the company expands to new markets. The team's prior experience at leading fintech companies mitigates these risks significantly.",
    },
    financialInfo: {
      capitalRaised: "$4.5M Seed round",
      leadInvestors: "Sequoia Capital Southeast Asia, Y Combinator",
      estimatedRevenue: "$1.2M ARR (as of Q4 2024)",
      burnRate: "$180K/month",
      runway: "18 months",
      capTableSummary: "Founders 65%, Sequoia 20%, YC 7%, Angels 8%",
    },
    competitiveInfo: {
      competitors: "Stripe, PayPal, Adyen, Bill.com, Tipalti",
      comparableCompanies: "Stripe (payments infrastructure), Bill.com (B2B payments), Ramp (embedded finance)",
      industryMultiples: "10-15x ARR for high-growth fintech companies",
    },
    customerMetrics: {
      customerRatings: "4.7/5 on G2, 4.8/5 on Capterra",
      engagement: "85% monthly active users, average 45 transactions per customer per month",
      feedback: "Customers praise ease of integration, responsive support, and financing options",
    },
    riskInfo: {
      regulatoryRisk:
        "Medium - Subject to financial regulations in Singapore, expanding to other markets requires compliance",
      ipPatents: "Proprietary underwriting algorithm (patent pending), API architecture (trade secret)",
    },
    opportunityInfo: {
      exitPotential: "High - Strategic acquisition target for Stripe, PayPal, or Square; IPO potential at scale",
      milestones: "Reached $1M ARR in 18 months, processed $50M in transactions, expanded to 3 countries",
      notablePartners: "Xero (accounting integration), Shopify (e-commerce integration), DBS Bank (banking partner)",
    },
    valuationInfo: {
      impliedValuationMultiples: "12x ARR based on $4.5M raise at $15M post-money valuation",
      comparableMultiple: "10-15x ARR for similar-stage fintech companies",
      revenueEstimate: "$3.5M ARR projected for end of 2025 (based on current growth rate)",
    },
  },
  {
    id: "6",
    name: "CloudSecure",
    sector: "Cybersecurity",
    stage: "Series A",
    country: "United States",
    description: "Zero-trust security platform for cloud infrastructure",
    team: "CEO: Alex Turner (ex-Palo Alto Networks), 18 security experts",
    metrics: "ARR: $2M, Growth: 200% YoY, Customers: 65 enterprises",
    score: 76,
    rank: 6,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 77,
      ml: 75,
      sentiment: 76,
    },
    rationale: {
      whyInvest: [
        "Cybersecurity is mission-critical for enterprises",
        "Zero-trust is the future of security",
        "Strong enterprise customer base",
        "CEO from leading security company",
      ],
      whyNot: ["Crowded cybersecurity market", "Long enterprise sales cycles"],
      keyStrengths:
        "CloudSecure addresses the critical need for zero-trust security in cloud environments with a comprehensive platform that integrates seamlessly with major cloud providers (AWS, Azure, GCP). The founding team's deep cybersecurity expertise from Palo Alto Networks and Cisco provides strong technical credibility and industry connections. With 65 enterprise customers including Fortune 500 companies, CloudSecure has demonstrated strong product-market fit in a mission-critical category. The 200% YoY growth and $2M ARR show strong market demand. Enterprise customers have high switching costs and long-term contracts, providing predictable recurring revenue and strong retention (92% net revenue retention).",
      areasOfConcern:
        "The cybersecurity market is highly competitive with well-funded incumbents like Palo Alto Networks, CrowdStrike, and Zscaler. Enterprise sales cycles are long (6-12 months), requiring significant sales and marketing investment to scale. The company's current burn rate of $250K/month with 16 months of runway means they'll need to raise additional capital soon. Customer concentration risk exists with top 5 customers representing 40% of revenue. The zero-trust security category is becoming crowded with many startups and incumbents pivoting to this approach. Technical complexity of the product requires significant customer education and implementation support.",
    },
    detailedMetrics: {
      arr: "$2M",
      growth: "200%",
      teamSize: 18,
      fundingStage: "Series A",
    },
    companyInfo: {
      founded: "2021",
      headquarters: "Palo Alto, CA",
      website: "https://cloudsecure.io",
      linkedin: "https://linkedin.com/company/cloudsecure",
      employeeCount: 28,
      fundingRaised: "$12M",
      founders: "Alex Turner (CEO, ex-Palo Alto Networks), Sarah Chen (CTO, ex-Cisco)",
      contactInfo: "contact@cloudsecure.io",
      location: "Palo Alto, California",
      area: "North America",
      ventureCapitalFirm: "Andreessen Horowitz, Sequoia Capital",
    },
    marketInfo: {
      industry: "Cybersecurity",
      subIndustry: "Cloud Security & Zero-Trust",
      marketSize: "$75B global cloud security market, growing at 18% CAGR",
      segment: "Enterprise Cloud Security",
      targetPersona: "CISOs and Security Directors at mid-market and enterprise companies",
      customerProfile: "Companies with 500+ employees using multi-cloud infrastructure",
      aiDisruptionPropensity: "Low - Security requires human expertise and judgment",
      marketFragmentation: "Moderately fragmented with several large players and many niche solutions",
      b2bOrB2c: "B2B",
      marketCompetitionAnalysis:
        "The cloud security market is valued at $75B globally and growing at 18% CAGR, driven by cloud adoption and increasing cyber threats. Zero-trust architecture is becoming the standard security model, with Gartner predicting 60% of enterprises will adopt zero-trust by 2025. Key competitors include Palo Alto Networks (Prisma Cloud), Zscaler (cloud-native security), CrowdStrike (endpoint + cloud), and Wiz (cloud security posture). CloudSecure differentiates through its unified platform approach that covers identity, network, and workload security in a single solution. The competitive moat strengthens with customer data and threat intelligence that improves over time. High switching costs and compliance requirements create customer stickiness once deployed.",
    },
    productInfo: {
      productName: "CloudSecure Platform",
      problemSolved:
        "Enterprises struggle to secure multi-cloud environments with fragmented tools and lack of visibility across cloud infrastructure",
      horizontalOrVertical: "Horizontal - Applicable across all industries using cloud infrastructure",
      moat: "Proprietary threat intelligence database, deep cloud provider integrations, network effects from shared threat data",
    },
    businessModelInfo: {
      modelType: "B2B SaaS with usage-based pricing",
      revenueModel: "Annual contracts with per-user and per-workload pricing tiers",
      pricingStrategy: "Tiered pricing: Starter ($50K/year), Professional ($150K/year), Enterprise (custom)",
      unitEconomics: "LTV:CAC ratio of 3.5:1, payback period of 14 months, gross margin 78%",
    },
    salesInfo: {
      salesMotion: "Enterprise sales with technical proof-of-concept",
      salesCycleLength: "6-12 months for enterprise deals",
      numberOfCustomers: "65 enterprise customers",
      customerValidation: "Strong - 92% net revenue retention, NPS of 62",
      gtmStrategy: "Direct enterprise sales, channel partnerships with cloud providers and MSSPs",
      channels: "Direct sales team, AWS/Azure/GCP marketplaces, security resellers",
      salesComplexity: "High - Requires technical evaluation, security team buy-in, and compliance review",
    },
    teamInfo: {
      teamDepth: "Strong security team with 18 engineers, 6 in sales, 3 in customer success, 1 in marketing",
      keyTeamMembers:
        "Alex Turner (CEO, 10 years at Palo Alto Networks), Sarah Chen (CTO, 8 years at Cisco), Mike Johnson (VP Sales, ex-CrowdStrike)",
      boardMembers: "Alex Turner (CEO), Sarah Chen (CTO), Marc Andreessen (a16z), Doug Leone (Sequoia)",
      advisors: "Nikesh Arora (Palo Alto Networks CEO), George Kurtz (CrowdStrike CEO)",
      foundersEducation: "Alex Turner: Stanford CS, MBA from Wharton; Sarah Chen: MIT CS, PhD from Berkeley",
      foundersPriorExperience:
        "Alex Turner: 10 years at Palo Alto Networks (Product Lead for Prisma Cloud), 3 years at Symantec. Sarah Chen: 8 years at Cisco (Security Architect), 4 years at FireEye",
      teamExecutionAssessment:
        "The founding team brings exceptional cybersecurity expertise with 18+ years of combined experience at leading security companies. Alex Turner led the Prisma Cloud product at Palo Alto Networks, giving him deep knowledge of cloud security and enterprise sales. Sarah Chen's 8 years at Cisco as a Security Architect provides strong technical leadership and understanding of enterprise security requirements. The team has successfully built and launched the platform, onboarded 65 enterprise customers, and achieved $2M ARR within 3 years. The advisory board includes CEOs of Palo Alto Networks and CrowdStrike, providing strategic guidance and industry credibility. Key execution risks include scaling the sales team while maintaining deal quality, and managing product complexity as new features are added. The team's prior experience at leading security companies significantly mitigates these risks.",
    },
    financialInfo: {
      capitalRaised: "$12M Series A",
      leadInvestors: "Andreessen Horowitz, Sequoia Capital",
      estimatedRevenue: "$2M ARR (as of Q4 2024)",
      burnRate: "$250K/month",
      runway: "16 months",
      capTableSummary: "Founders 55%, a16z 25%, Sequoia 15%, Angels 5%",
    },
    competitiveInfo: {
      competitors: "Palo Alto Networks (Prisma Cloud), Zscaler, CrowdStrike, Wiz, Lacework",
      comparableCompanies: "Wiz (cloud security), Lacework (cloud security), Orca Security (agentless security)",
      industryMultiples: "15-20x ARR for high-growth cybersecurity companies",
    },
    customerMetrics: {
      customerRatings: "4.6/5 on Gartner Peer Insights, 4.5/5 on G2",
      engagement: "92% net revenue retention, average customer uses 85% of platform features",
      feedback: "Customers praise comprehensive coverage, ease of deployment, and responsive support team",
    },
    riskInfo: {
      regulatoryRisk:
        "Low - Cybersecurity products help customers meet compliance requirements (SOC 2, ISO 27001, GDPR)",
      ipPatents: "3 patents pending on zero-trust architecture and threat detection algorithms",
    },
    opportunityInfo: {
      exitPotential:
        "High - Strategic acquisition target for Palo Alto Networks, Cisco, Microsoft, or Google; IPO potential at scale",
      milestones: "Reached $2M ARR in 3 years, onboarded 5 Fortune 500 customers, expanded to EMEA region",
      notablePartners: "AWS (Technology Partner), Microsoft Azure (Security Partner), Google Cloud (Partner)",
    },
    valuationInfo: {
      impliedValuationMultiples: "15x ARR based on $12M raise at $30M post-money valuation",
      comparableMultiple: "15-20x ARR for similar-stage cybersecurity companies",
      revenueEstimate: "$6M ARR projected for end of 2025 (based on current growth rate)",
    },
  },
  {
    id: "7",
    name: "FoodChain",
    sector: "Supply Chain",
    stage: "Seed",
    country: "Netherlands",
    description: "Blockchain-based food supply chain tracking and verification",
    team: "CEO: Jennifer Wu, CTO: Mark Stevens, 10 team members",
    metrics: "ARR: $600K, Growth: 150% YoY, Partners: 40 suppliers",
    score: 73,
    rank: 7,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 74,
      ml: 72,
      sentiment: 73,
    },
    rationale: {
      whyInvest: [
        "Food safety and traceability are critical issues",
        "Blockchain provides transparency and trust",
        "Growing network of 40 supplier partners",
        "Regulatory tailwinds for supply chain transparency",
      ],
      whyNot: ["Blockchain adoption can be slow", "Requires significant partner onboarding"],
    },
    detailedMetrics: {
      arr: "$600K",
      growth: "150%",
      teamSize: 10,
      fundingStage: "Seed",
    },
  },
  {
    id: "8",
    name: "RetailOS",
    sector: "Retail Technology",
    stage: "Series A",
    country: "Canada",
    description: "Unified commerce platform for omnichannel retail operations",
    team: "CEO: Tom Anderson (ex-Shopify), 22 employees",
    metrics: "ARR: $1.5M, Growth: 190% YoY, Merchants: 200",
    score: 70,
    rank: 8,
    feedback: [],
    pipelineStage: "Intro Sent",
    aiScores: {
      llm: 71,
      ml: 69,
      sentiment: 70,
    },
    rationale: {
      whyInvest: [
        "Omnichannel retail is essential for modern commerce",
        "Ex-Shopify CEO knows the space well",
        "200 merchants provide validation",
        "Strong growth at 190% YoY",
      ],
      whyNot: ["Competing with Shopify and other giants", "Retail margins can be thin"],
    },
    detailedMetrics: {
      arr: "$1.5M",
      growth: "190%",
      teamSize: 22,
      fundingStage: "Series A",
    },
  },
  {
    id: "9",
    name: "PropTech Innovations",
    sector: "Real Estate Technology",
    stage: "Seed",
    country: "Australia",
    description: "AI-powered property valuation and investment analysis platform",
    team: "CEO: Rachel Brown, CTO: Dr. James Wilson, 8 team members including 3 data scientists",
    metrics: "ARR: $500K, Growth: 160% YoY, Properties analyzed: 10K+",
    score: 67,
    rank: 9,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 68,
      ml: 66,
      sentiment: 67,
    },
    rationale: {
      whyInvest: [
        "Real estate is a massive asset class",
        "AI-powered valuations add significant value",
        "10K+ properties analyzed shows traction",
        "Data moat grows with usage",
      ],
      whyNot: ["Real estate market can be cyclical", "Requires significant data to be accurate"],
      keyStrengths:
        "PropTech Innovations has built a proprietary AI valuation model trained on 10K+ property transactions, providing more accurate valuations than traditional methods (95% accuracy vs 85% industry average). The platform addresses a critical pain point for real estate investors who struggle with time-consuming manual analysis and inconsistent valuation methods. With 160% YoY growth and $500K ARR, the company demonstrates strong product-market fit in the Australian market. The data moat strengthens with each property analyzed, creating a competitive advantage that's difficult to replicate. The founding team includes experienced data scientists and real estate professionals, combining technical expertise with domain knowledge.",
      areasOfConcern:
        "The real estate market is cyclical and sensitive to interest rates and economic conditions, which could impact demand for the platform. The company is currently focused only on the Australian market, limiting near-term growth potential until international expansion. Accuracy of AI valuations depends on data quality and market conditions, and any high-profile valuation errors could damage reputation. Competition from established real estate data providers like CoreLogic and REA Group poses a threat. The current burn rate of $80K/month with 15 months of runway means the company will need to raise additional capital soon. Customer acquisition in real estate can be relationship-driven, requiring significant time to build trust and credibility.",
    },
    detailedMetrics: {
      arr: "$500K",
      growth: "160%",
      teamSize: 8,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Sydney, Australia",
      website: "https://proptechinnovations.com.au",
      linkedin: "https://linkedin.com/company/proptech-innovations",
      employeeCount: 12,
      fundingRaised: "$2.5M",
      founders: "Rachel Brown (CEO), Dr. James Wilson (Chief Data Scientist)",
      contactInfo: "contact@proptechinnovations.com.au",
      location: "Sydney, New South Wales",
      area: "Australia & New Zealand",
      ventureCapitalFirm: "Blackbird Ventures, Square Peg Capital",
    },
    marketInfo: {
      industry: "Real Estate Technology",
      subIndustry: "Property Valuation & Investment Analytics",
      marketSize: "$12B Australian property technology market",
      segment: "Real Estate Investors & Property Professionals",
      targetPersona: "Real estate investors, property developers, and real estate agents",
      customerProfile: "Individual investors and small property investment firms managing 5-50 properties",
      aiDisruptionPropensity: "High - AI can significantly improve valuation accuracy and speed",
      marketFragmentation: "Moderately fragmented with established players and emerging startups",
      b2bOrB2c: "B2B",
      marketCompetitionAnalysis:
        "The Australian property technology market is valued at $12B and growing at 12% CAGR, driven by digitization of real estate transactions and demand for data-driven investment decisions. Key competitors include CoreLogic (dominant in property data), REA Group (property listings and data), and Domain (property portal with analytics). PropTech Innovations differentiates through its AI-powered valuation model that provides more accurate and faster valuations than traditional methods. The competitive moat strengthens with proprietary data from 10K+ analyzed properties and machine learning models that improve over time. Regulatory requirements for property valuations create barriers to entry, favoring established players with credibility and track records.",
    },
    productInfo: {
      productName: "PropTech Valuation Platform",
      problemSolved:
        "Real estate investors spend hours manually analyzing properties with inconsistent valuation methods and limited data insights",
      horizontalOrVertical: "Vertical - Focused specifically on real estate investment analysis",
      moat: "Proprietary AI valuation model trained on 10K+ properties, exclusive data partnerships, network effects from user-generated data",
    },
    businessModelInfo: {
      modelType: "B2B SaaS with tiered subscriptions",
      revenueModel: "Monthly subscription ($99-$499/month) + per-valuation fees for high-volume users",
      pricingStrategy: "Freemium model with 5 free valuations, then tiered pricing based on usage volume",
      unitEconomics: "LTV:CAC ratio of 3:1, payback period of 12 months, gross margin 82%",
    },
    salesInfo: {
      salesMotion: "Product-led growth with self-service signup and sales-assisted for enterprise",
      salesCycleLength: "7-14 days for individual investors, 30-60 days for property firms",
      numberOfCustomers: "450 active subscribers",
      customerValidation: "Strong - 88% customer retention, NPS of 55",
      gtmStrategy:
        "Content marketing targeting real estate investors, partnerships with real estate agencies, SEO for property valuation keywords",
      channels: "Direct website signup, real estate agency partnerships, property investment forums and communities",
      salesComplexity: "Low to Medium - Self-service for individuals, requires demo and training for firms",
    },
    teamInfo: {
      teamDepth: "Strong data science team with 3 PhDs, 2 in product, 2 in sales, 1 in marketing",
      keyTeamMembers:
        "Rachel Brown (CEO, 12 years in real estate), Dr. James Wilson (Chief Data Scientist, PhD in ML), Sarah Lee (Head of Product, ex-REA Group)",
      boardMembers:
        "Rachel Brown (CEO), Dr. James Wilson (CDS), Rick Baker (Blackbird Ventures), Niki Scevak (Square Peg)",
      advisors:
        "Simon Baker (ex-CEO of REA Group), Prof. Michael Chen (UNSW Real Estate), Lisa Wong (Property Investment Expert)",
      foundersEducation:
        "Rachel Brown: MBA from Melbourne Business School; Dr. James Wilson: PhD in Machine Learning from Stanford, BS from MIT",
      foundersPriorExperience:
        "Rachel Brown: 12 years in real estate (8 years as property investor, 4 years at major real estate firm). Dr. James Wilson: 5 years at Google (ML Research), 3 years at Zillow (Valuation Models)",
      teamExecutionAssessment:
        "The founding team combines deep real estate domain expertise with cutting-edge AI/ML capabilities. Rachel Brown's 12 years in real estate provides credibility and understanding of investor pain points. Dr. James Wilson's PhD in ML from Stanford and 5 years at Google brings world-class technical expertise in building accurate prediction models. The team has successfully built and launched the platform, analyzed 10K+ properties, and onboarded 450 subscribers within 2 years - demonstrating strong execution velocity. The advisory board includes the ex-CEO of REA Group (Australia's leading property portal), providing strategic guidance and industry connections. Key execution risks include scaling the data science team while maintaining model accuracy, and expanding beyond Australia to new markets with different property data. The team's complementary skills and prior experience significantly mitigate these risks.",
    },
    financialInfo: {
      capitalRaised: "$2.5M Seed round",
      leadInvestors: "Blackbird Ventures, Square Peg Capital",
      estimatedRevenue: "$500K ARR (as of Q4 2024)",
      burnRate: "$80K/month",
      runway: "15 months",
      capTableSummary: "Founders 70%, Blackbird 18%, Square Peg 10%, Angels 2%",
    },
    competitiveInfo: {
      competitors: "CoreLogic, REA Group, Domain, Pricefinder, RP Data",
      comparableCompanies: "Zillow (US property data), Redfin (US real estate tech), Opendoor (iBuying)",
      industryMultiples: "8-12x ARR for high-growth proptech companies",
    },
    customerMetrics: {
      customerRatings: "4.5/5 on Product Hunt, 4.3/5 on Capterra",
      engagement: "88% monthly active users, average 12 property valuations per user per month",
      feedback: "Users praise valuation accuracy, speed of analysis, and comprehensive property insights",
    },
    riskInfo: {
      regulatoryRisk:
        "Medium - Property valuations may require licensing in some jurisdictions; data privacy regulations apply",
      ipPatents:
        "Proprietary AI valuation algorithm (patent pending), property data aggregation methods (trade secret)",
    },
    opportunityInfo: {
      exitPotential:
        "Medium to High - Strategic acquisition target for REA Group, Domain, or CoreLogic; potential for regional expansion to Asia-Pacific",
      milestones:
        "Analyzed 10K+ properties, reached $500K ARR in 2 years, achieved 95% valuation accuracy, expanded to Melbourne and Brisbane markets",
      notablePartners:
        "Ray White (real estate agency partnership), LJ Hooker (data partnership), ANZ Bank (mortgage referral partner)",
    },
    valuationInfo: {
      impliedValuationMultiples: "10x ARR based on $2.5M raise at $5M post-money valuation",
      comparableMultiple: "8-12x ARR for similar-stage proptech companies",
      revenueEstimate: "$1.3M ARR projected for end of 2025 (based on current growth rate)",
    },
  },
  {
    id: "10",
    name: "MobilityNext",
    sector: "Transportation",
    stage: "Series A",
    country: "United States",
    description: "Fleet management and route optimization for logistics companies",
    team: "CEO: Chris Martinez (ex-Uber), 16 employees",
    metrics: "ARR: $1.3M, Growth: 170% YoY, Vehicles managed: 5K+",
    score: 64,
    rank: 10,
    feedback: [],
    pipelineStage: "Term Sheet",
    aiScores: {
      llm: 65,
      ml: 63,
      sentiment: 64,
    },
    rationale: {
      whyInvest: [
        "Logistics is a huge, growing market",
        "Fleet optimization provides clear ROI",
        "Ex-Uber CEO understands mobility",
        "Managing 5K+ vehicles shows scale",
      ],
      whyNot: ["Competitive logistics software market", "Hardware dependencies can be challenging"],
    },
    detailedMetrics: {
      arr: "$1.3M",
      growth: "170%",
      teamSize: 16,
      fundingStage: "Series A",
    },
    companyInfo: {
      founded: "2021",
      headquarters: "San Francisco, CA",
      website: "https://mobilitynext.com",
      linkedin: "https://linkedin.com/company/mobilitynext",
      employeeCount: 20,
      fundingRaised: "$7.5M",
    },
  },
  {
    id: "11",
    name: "AgriTech Solutions",
    sector: "Agriculture Technology",
    stage: "Seed",
    country: "India",
    description: "IoT sensors and analytics for precision agriculture",
    team: "CEO: Emily Johnson, CTO: Kevin White, 9 team members",
    metrics: "ARR: $400K, Growth: 140% YoY, Farms: 80",
    score: 61,
    rank: 11,
    feedback: [],
    pipelineStage: "Deal Flow",
    aiScores: {
      llm: 62,
      ml: 60,
      sentiment: 61,
    },
    rationale: {
      whyInvest: [
        "Agriculture tech addresses food security",
        "IoT sensors provide actionable data",
        "80 farms provide early validation",
        "Large addressable market globally",
      ],
      whyNot: ["Agriculture can have thin margins", "Farmers may be slow to adopt new tech"],
    },
    detailedMetrics: {
      arr: "$400K",
      growth: "140%",
      teamSize: 9,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Bangalore, India",
      website: "https://agritechsolutions.com",
      linkedin: "https://linkedin.com/company/agritechsolutions",
      employeeCount: 15,
      fundingRaised: "$3.0M",
    },
  },
  {
    id: "12",
    name: "MediaStream Pro",
    sector: "Media & Entertainment",
    stage: "Series A",
    country: "United States",
    description: "Content delivery network optimized for live streaming",
    team: "CEO: Daniel Lee (ex-Netflix), 14 engineers",
    metrics: "ARR: $1.1M, Growth: 175% YoY, Streams: 2M monthly",
    score: 58,
    rank: 12,
    feedback: [],
    pipelineStage: "Closed",
    aiScores: {
      llm: 59,
      ml: 57,
      sentiment: 58,
    },
    rationale: {
      whyInvest: [
        "Live streaming continues to grow",
        "Ex-Netflix CEO brings streaming expertise",
        "2M monthly streams show usage",
        "CDN infrastructure has high margins",
      ],
      whyNot: ["Competing with AWS, Cloudflare, etc.", "High infrastructure costs"],
    },
    detailedMetrics: {
      arr: "$1.1M",
      growth: "175%",
      teamSize: 14,
      fundingStage: "Series A",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Los Angeles, CA",
      website: "https://mediastreamp.io",
      linkedin: "https://linkedin.com/company/mediastreamp",
      employeeCount: 25,
      fundingRaised: "$10M",
    },
  },
]
