import type { Startup } from "./types"

export const dummyStartups: Startup[] = [
  {
    id: "1",
    name: "TechFlow AI",
    sector: "Artificial Intelligence",
    stage: "Series A",
    country: "United States",
    description: "AI-powered workflow automation platform for enterprise teams",
    team: "CEO: Sarah Chen (ex-Google), CTO: Michael Park (ex-Meta), 15 engineers",
    metrics: "ARR: $2.5M, Growth: 300% YoY, Customers: 45 enterprise clients",
    score: 92,
    rank: 1,
    feedback: [],
    pipelineStage: "Due Diligence",
    aiScores: {
      llm: 94,
      ml: 91,
      sentiment: 90,
      llmAnalysis:
        "The LLM analysis indicates exceptional market positioning with strong product-market fit. The company demonstrates clear differentiation through its AI-powered automation capabilities, addressing a significant pain point in enterprise workflows. The founding team's background at leading tech companies provides credibility and deep technical expertise.",
      mlAnalysis:
        "Machine learning models predict high success probability based on growth metrics, team composition, and market dynamics. The 300% YoY growth rate significantly exceeds industry benchmarks. Customer retention data and expansion revenue patterns suggest strong product stickiness and increasing customer lifetime value.",
      sentimentAnalysis:
        "Market sentiment analysis shows overwhelmingly positive signals from industry analysts, early customers, and technology media. The company is frequently mentioned in discussions about the future of enterprise automation. Customer testimonials highlight significant productivity gains and ROI, with an average satisfaction score of 4.8/5.",
    },
    rationale: {
      whyInvest: [
        "Strong founding team with FAANG experience",
        "Exceptional 300% YoY growth rate",
        "Large addressable market in enterprise automation",
        "High customer retention and expansion revenue",
      ],
      whyNot: ["Competitive market with established players", "Relatively early stage with execution risk"],
    },
    detailedMetrics: {
      arr: "$2.5M",
      growth: "300%",
      teamSize: 15,
      fundingStage: "Series A",
    },
    companyInfo: {
      founded: "2021",
      headquarters: "San Francisco, CA",
      website: "https://techflowai.com",
      linkedin: "https://linkedin.com/company/techflowai",
      employeeCount: 28,
      fundingRaised: "$8.5M",
    },
  },
  {
    id: "2",
    name: "HealthSync",
    sector: "Healthcare",
    stage: "Seed",
    country: "United States",
    description: "Patient data synchronization platform for healthcare providers",
    team: "CEO: Dr. James Wilson (MD, Stanford), CTO: Lisa Zhang, 8 team members",
    metrics: "ARR: $800K, Growth: 250% YoY, Customers: 120 clinics",
    score: 88,
    rank: 2,
    feedback: [],
    pipelineStage: "Partner Review",
    aiScores: {
      llm: 89,
      ml: 87,
      sentiment: 88,
      llmAnalysis:
        "Healthcare interoperability remains a critical challenge, and HealthSync addresses this with a well-designed solution. The CEO's medical background provides unique domain expertise that competitors lack. The platform's HIPAA compliance and security features are robust, meeting stringent healthcare requirements.",
      mlAnalysis:
        "Predictive models show strong growth trajectory with 120 clinics already onboarded. The healthcare vertical typically has high switching costs, suggesting strong customer retention. Revenue per clinic is growing steadily, indicating successful upselling and feature adoption.",
      sentimentAnalysis:
        "Healthcare providers express high satisfaction with the platform's ease of use and integration capabilities. Industry publications have featured HealthSync as an emerging leader in healthcare data management. Regulatory compliance and data security receive consistently positive feedback from users.",
    },
    rationale: {
      whyInvest: [
        "Healthcare is a massive, growing market",
        "Strong product-market fit with 120 clinics",
        "CEO has deep domain expertise as MD",
        "Impressive growth trajectory at 250% YoY",
      ],
      whyNot: ["Healthcare sales cycles can be long", "Regulatory compliance adds complexity"],
    },
    detailedMetrics: {
      arr: "$800K",
      growth: "250%",
      teamSize: 8,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Boston, MA",
      website: "https://healthsync.io",
      linkedin: "https://linkedin.com/company/healthsync",
      employeeCount: 15,
      fundingRaised: "$3.2M",
    },
  },
  {
    id: "3",
    name: "GreenEnergy Solutions",
    sector: "Clean Energy",
    stage: "Series B",
    country: "Germany",
    description: "Smart grid optimization software for renewable energy distribution",
    team: "CEO: Robert Green (ex-Tesla), 25 employees across engineering and sales",
    metrics: "ARR: $5M, Growth: 180% YoY, Customers: 30 utility companies",
    score: 85,
    rank: 3,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 86,
      ml: 84,
      sentiment: 85,
    },
    rationale: {
      whyInvest: [
        "Clean energy is a high-priority sector globally",
        "Strong revenue at $5M ARR",
        "Ex-Tesla CEO brings valuable experience",
        "Utility companies provide stable, recurring revenue",
      ],
      whyNot: ["Capital-intensive industry", "Dependent on government energy policies"],
    },
    detailedMetrics: {
      arr: "$5M",
      growth: "180%",
      teamSize: 25,
      fundingStage: "Series B",
    },
  },
  {
    id: "4",
    name: "EduTech Pro",
    sector: "Education Technology",
    stage: "Series A",
    country: "United Kingdom",
    description: "Adaptive learning platform with AI-powered personalization",
    team: "CEO: Maria Rodriguez (ex-Coursera), 20 team members",
    metrics: "ARR: $1.8M, Growth: 220% YoY, Users: 50K students",
    score: 82,
    rank: 4,
    feedback: [],
    pipelineStage: "Intro Sent",
    aiScores: {
      llm: 83,
      ml: 81,
      sentiment: 82,
    },
    rationale: {
      whyInvest: [
        "EdTech market continues to expand post-pandemic",
        "Strong user base of 50K students",
        "CEO has proven track record at Coursera",
        "AI personalization is a key differentiator",
      ],
      whyNot: ["Education budgets can be constrained", "High customer acquisition costs"],
    },
    detailedMetrics: {
      arr: "$1.8M",
      growth: "220%",
      teamSize: 20,
      fundingStage: "Series A",
    },
  },
  {
    id: "5",
    name: "FinanceHub",
    sector: "Fintech",
    stage: "Seed",
    country: "Singapore",
    description: "B2B payment processing with embedded finance solutions",
    team: "CEO: David Kim (ex-Stripe), CTO: Anna Lee, 12 engineers",
    metrics: "ARR: $1.2M, Growth: 280% YoY, Transaction volume: $50M",
    score: 79,
    rank: 5,
    feedback: [],
    pipelineStage: "Deal Flow",
    aiScores: {
      llm: 80,
      ml: 78,
      sentiment: 79,
      llmAnalysis:
        "FinanceHub demonstrates strong understanding of B2B payment flows and embedded finance opportunities. The CEO's experience at Stripe provides valuable insights into payment infrastructure and go-to-market strategies. The platform's API-first approach enables rapid integration for customers.",
      mlAnalysis:
        "Growth metrics show consistent month-over-month improvement with $50M in transaction volume processed. The take rate and unit economics are healthy, with clear path to profitability. Customer acquisition costs are declining as the product gains market traction and word-of-mouth referrals increase.",
      sentimentAnalysis:
        "Early customers praise the platform's developer-friendly API and comprehensive documentation. The fintech community views FinanceHub as a promising player in the embedded finance space. Social media sentiment and online reviews are predominantly positive, with users highlighting ease of integration and reliable service.",
    },
    rationale: {
      whyInvest: [
        "Fintech is a high-growth sector",
        "Ex-Stripe CEO understands payments deeply",
        "Strong transaction volume of $50M",
        "Embedded finance is a growing trend",
      ],
      whyNot: ["Highly competitive fintech landscape", "Regulatory challenges in multiple markets"],
    },
    detailedMetrics: {
      arr: "$1.2M",
      growth: "280%",
      teamSize: 12,
      fundingStage: "Seed",
    },
    companyInfo: {
      founded: "2022",
      headquarters: "Singapore",
      website: "https://financehub.sg",
      linkedin: "https://linkedin.com/company/financehub",
      employeeCount: 18,
      fundingRaised: "$4.5M",
      founders: "David Kim (CEO, ex-Stripe), Anna Lee (CTO, ex-PayPal)",
      contactInfo: "contact@financehub.sg",
    },
    marketInfo: {
      industry: "Financial Technology",
      subIndustry: "B2B Payments & Embedded Finance",
      marketSize: "$2.1T global B2B payments market",
      segment: "SMB and Mid-Market B2B Commerce",
      targetPersona: "CFOs and Finance Teams at B2B companies",
      customerProfile: "B2B companies with $5M-$100M revenue processing recurring payments",
      aiDisruptionPropensity: "Medium - AI can optimize fraud detection and underwriting",
      marketFragmentation: "Highly fragmented with regional players and legacy systems",
    },
    productInfo: {
      productName: "FinanceHub Platform",
      problemSolved:
        "Complex B2B payment processing with poor integration, high fees, and limited financing options for buyers",
      painIntensity: "High - Payment delays and financing gaps directly impact cash flow and growth",
      productStatus: "Live in production with 85+ active customers",
      horizontalOrVertical: "Horizontal - Applicable across B2B industries",
      stackPosition: "Infrastructure layer - Payment processing and embedded finance",
      uniqueFeatures:
        "API-first architecture, embedded financing options, multi-currency support, automated reconciliation",
      adoption: "Strong adoption with 280% YoY growth and $50M transaction volume",
      valueProp: "Reduce payment processing costs by 40%, accelerate cash collection by 15 days, offer buyer financing",
      moat: "Network effects from buyer-seller connections, proprietary underwriting data, integration partnerships",
    },
    businessModelInfo: {
      modelType: "B2B SaaS + Transaction Fees",
      revenueModel: "Platform fee (0.5-1.5% of transaction value) + monthly subscription ($500-$5K)",
      pricingStrategy: "Tiered pricing based on transaction volume with enterprise custom pricing",
      unitEconomics: "LTV:CAC ratio of 4:1, payback period of 8 months, gross margin 75%",
      capitalIntensity: "Low - Software-based with minimal infrastructure costs",
    },
    salesInfo: {
      salesMotion: "Product-led growth with sales-assisted conversion for enterprise",
      salesCycleLength: "30-60 days for SMB, 90-120 days for enterprise",
      numberOfCustomers: "85 active customers",
      customerValidation: "Strong - 95% customer retention, NPS of 68",
      gtmStrategy: "Developer-first approach with API documentation, partnerships with accounting software",
      channels: "Direct sales, partner referrals, developer community, content marketing",
      salesComplexity: "Medium - Requires technical integration and finance team buy-in",
      adoptionRate: "Fast - Average time to first transaction is 14 days",
    },
    teamInfo: {
      teamDepth: "Strong technical team with 12 engineers, 3 in sales, 2 in operations, 1 in finance",
      keyTeamMembers:
        "David Kim (CEO, 8 years at Stripe), Anna Lee (CTO, 6 years at PayPal), Sarah Tan (Head of Sales, ex-Square)",
      boardMembers: "David Kim (CEO), Anna Lee (CTO), Michael Chen (Investor, Sequoia), Lisa Wong (Independent)",
      advisors: "Patrick Collison (Stripe Co-founder), John Doerr (Kleiner Perkins), Amy Chang (ex-Google Payments)",
    },
    financialInfo: {
      capitalRaised: "$4.5M Seed round",
      leadInvestors: "Sequoia Capital Southeast Asia, Y Combinator",
      estimatedRevenue: "$1.2M ARR (as of Q4 2024)",
      burnRate: "$180K/month",
      runway: "18 months",
      capTableSummary: "Founders 65%, Sequoia 20%, YC 7%, Angels 8%",
    },
    competitiveInfo: {
      competitors: "Stripe, PayPal, Adyen, Bill.com, Tipalti",
      comparableCompanies: "Stripe (payments infrastructure), Bill.com (B2B payments), Ramp (embedded finance)",
      industryMultiples: "10-15x ARR for high-growth fintech companies",
    },
    customerMetrics: {
      customerRatings: "4.7/5 on G2, 4.8/5 on Capterra",
      engagement: "85% monthly active users, average 45 transactions per customer per month",
      feedback: "Customers praise ease of integration, responsive support, and financing options",
    },
    riskInfo: {
      regulatoryRisk:
        "Medium - Subject to financial regulations in Singapore, expanding to other markets requires compliance",
      ipPatents: "Proprietary underwriting algorithm (patent pending), API architecture (trade secret)",
    },
    opportunityInfo: {
      exitPotential: "High - Strategic acquisition target for Stripe, PayPal, or Square; IPO potential at scale",
      milestones: "Reached $1M ARR in 18 months, processed $50M in transactions, expanded to 3 countries",
      notablePartners: "Xero (accounting integration), Shopify (e-commerce integration), DBS Bank (banking partner)",
    },
    valuationInfo: {
      impliedValuationMultiples: "12x ARR based on $4.5M raise at $15M post-money valuation",
      comparableMultiple: "10-15x ARR for similar-stage fintech companies",
      revenueEstimate: "$3.5M ARR projected for end of 2025 (based on current growth rate)",
    },
  },
  {
    id: "6",
    name: "CloudSecure",
    sector: "Cybersecurity",
    stage: "Series A",
    country: "United States",
    description: "Zero-trust security platform for cloud infrastructure",
    team: "CEO: Alex Turner (ex-Palo Alto Networks), 18 security experts",
    metrics: "ARR: $2M, Growth: 200% YoY, Customers: 65 enterprises",
    score: 76,
    rank: 6,
    feedback: [],
    pipelineStage: "Deal Flow",
    aiScores: {
      llm: 77,
      ml: 75,
      sentiment: 76,
    },
    rationale: {
      whyInvest: [
        "Cybersecurity is mission-critical for enterprises",
        "Zero-trust is the future of security",
        "Strong enterprise customer base",
        "CEO from leading security company",
      ],
      whyNot: ["Crowded cybersecurity market", "Long enterprise sales cycles"],
    },
    detailedMetrics: {
      arr: "$2M",
      growth: "200%",
      teamSize: 18,
      fundingStage: "Series A",
    },
  },
  {
    id: "7",
    name: "FoodChain",
    sector: "Supply Chain",
    stage: "Seed",
    country: "Netherlands",
    description: "Blockchain-based food supply chain tracking and verification",
    team: "CEO: Jennifer Wu, CTO: Mark Stevens, 10 team members",
    metrics: "ARR: $600K, Growth: 150% YoY, Partners: 40 suppliers",
    score: 73,
    rank: 7,
    feedback: [],
    pipelineStage: "First Meeting",
    aiScores: {
      llm: 74,
      ml: 72,
      sentiment: 73,
    },
    rationale: {
      whyInvest: [
        "Food safety and traceability are critical issues",
        "Blockchain provides transparency and trust",
        "Growing network of 40 supplier partners",
        "Regulatory tailwinds for supply chain transparency",
      ],
      whyNot: ["Blockchain adoption can be slow", "Requires significant partner onboarding"],
    },
    detailedMetrics: {
      arr: "$600K",
      growth: "150%",
      teamSize: 10,
      fundingStage: "Seed",
    },
  },
  {
    id: "8",
    name: "RetailOS",
    sector: "Retail Technology",
    stage: "Series A",
    country: "Canada",
    description: "Unified commerce platform for omnichannel retail operations",
    team: "CEO: Tom Anderson (ex-Shopify), 22 employees",
    metrics: "ARR: $1.5M, Growth: 190% YoY, Merchants: 200",
    score: 70,
    rank: 8,
    feedback: [],
    pipelineStage: "Intro Sent",
    aiScores: {
      llm: 71,
      ml: 69,
      sentiment: 70,
    },
    rationale: {
      whyInvest: [
        "Omnichannel retail is essential for modern commerce",
        "Ex-Shopify CEO knows the space well",
        "200 merchants provide validation",
        "Strong growth at 190% YoY",
      ],
      whyNot: ["Competing with Shopify and other giants", "Retail margins can be thin"],
    },
    detailedMetrics: {
      arr: "$1.5M",
      growth: "190%",
      teamSize: 22,
      fundingStage: "Series A",
    },
  },
  {
    id: "9",
    name: "PropTech Innovations",
    sector: "Real Estate Technology",
    stage: "Seed",
    country: "Australia",
    description: "AI-powered property valuation and investment analysis platform",
    team: "CEO: Rachel Brown, 8 team members including 3 data scientists",
    metrics: "ARR: $500K, Growth: 160% YoY, Properties analyzed: 10K+",
    score: 67,
    rank: 9,
    feedback: [],
    pipelineStage: "Deal Flow",
    aiScores: {
      llm: 68,
      ml: 66,
      sentiment: 67,
    },
    rationale: {
      whyInvest: [
        "Real estate is a massive asset class",
        "AI-powered valuations add significant value",
        "10K+ properties analyzed shows traction",
        "Data moat grows with usage",
      ],
      whyNot: ["Real estate market can be cyclical", "Requires significant data to be accurate"],
    },
    detailedMetrics: {
      arr: "$500K",
      growth: "160%",
      teamSize: 8,
      fundingStage: "Seed",
    },
  },
  {
    id: "10",
    name: "MobilityNext",
    sector: "Transportation",
    stage: "Series A",
    country: "United States",
    description: "Fleet management and route optimization for logistics companies",
    team: "CEO: Chris Martinez (ex-Uber), 16 employees",
    metrics: "ARR: $1.3M, Growth: 170% YoY, Vehicles managed: 5K+",
    score: 64,
    rank: 10,
    feedback: [],
    pipelineStage: "Term Sheet",
    aiScores: {
      llm: 65,
      ml: 63,
      sentiment: 64,
    },
    rationale: {
      whyInvest: [
        "Logistics is a huge, growing market",
        "Fleet optimization provides clear ROI",
        "Ex-Uber CEO understands mobility",
        "Managing 5K+ vehicles shows scale",
      ],
      whyNot: ["Competitive logistics software market", "Hardware dependencies can be challenging"],
    },
    detailedMetrics: {
      arr: "$1.3M",
      growth: "170%",
      teamSize: 16,
      fundingStage: "Series A",
    },
  },
  {
    id: "11",
    name: "AgriTech Solutions",
    sector: "Agriculture Technology",
    stage: "Seed",
    country: "India",
    description: "IoT sensors and analytics for precision agriculture",
    team: "CEO: Emily Johnson, CTO: Kevin White, 9 team members",
    metrics: "ARR: $400K, Growth: 140% YoY, Farms: 80",
    score: 61,
    rank: 11,
    feedback: [],
    pipelineStage: "Deal Flow",
    aiScores: {
      llm: 62,
      ml: 60,
      sentiment: 61,
    },
    rationale: {
      whyInvest: [
        "Agriculture tech addresses food security",
        "IoT sensors provide actionable data",
        "80 farms provide early validation",
        "Large addressable market globally",
      ],
      whyNot: ["Agriculture can have thin margins", "Farmers may be slow to adopt new tech"],
    },
    detailedMetrics: {
      arr: "$400K",
      growth: "140%",
      teamSize: 9,
      fundingStage: "Seed",
    },
  },
  {
    id: "12",
    name: "MediaStream Pro",
    sector: "Media & Entertainment",
    stage: "Series A",
    country: "United States",
    description: "Content delivery network optimized for live streaming",
    team: "CEO: Daniel Lee (ex-Netflix), 14 engineers",
    metrics: "ARR: $1.1M, Growth: 175% YoY, Streams: 2M monthly",
    score: 58,
    rank: 12,
    feedback: [],
    pipelineStage: "Closed",
    aiScores: {
      llm: 59,
      ml: 57,
      sentiment: 58,
    },
    rationale: {
      whyInvest: [
        "Live streaming continues to grow",
        "Ex-Netflix CEO brings streaming expertise",
        "2M monthly streams show usage",
        "CDN infrastructure has high margins",
      ],
      whyNot: ["Competing with AWS, Cloudflare, etc.", "High infrastructure costs"],
    },
    detailedMetrics: {
      arr: "$1.1M",
      growth: "175%",
      teamSize: 14,
      fundingStage: "Series A",
    },
  },
]
