import type { ScorecardCriterion } from "./types"

export const SCORECARD_TEMPLATE: ScorecardCriterion[] = [
  // MARKET Section (30% total)
  {
    section: "MARKET",
    criterion: "Market Size & Growth",
    guidingQuestions: "How big is the TAM/SAM? Growth rate? VC-scale today or via adjacencies?",
    low: "< $5B and flat/declining",
    medium: "$5–10B, 5–10% CAGR",
    high: "$10B+, 15%+ CAGR and/or adjacencies to expand TAM",
    weight: 12,
  },
  {
    section: "MARKET",
    criterion: "Timing & Macro Drivers",
    guidingQuestions: "Why now? Any macro/tech/regulatory tailwinds?",
    low: "No clear drivers; headwinds likely",
    medium: "Some supportive trends; mixed signals",
    high: "Strong secular shift (regulatory, tech platform change, behavior)",
    weight: 10,
  },
  {
    section: "MARKET",
    criterion: "Customer Pain Intensity",
    guidingQuestions: "How urgent/critical is the problem? Willingness to pay?",
    low: "Nice-to-have; low urgency",
    medium: "Important but not urgent; moderate WTP",
    high: "Mission-critical; budgeted; high WTP",
    weight: 8,
  },
  // TEAM Section (20% total)
  {
    section: "TEAM",
    criterion: "Founder–Market Fit",
    guidingQuestions: "Do founders have unique insight, unfair advantage, or lived experience?",
    low: "No relevant experience or weak founder–problem link",
    medium: "Some industry exposure; partial insight",
    high: "Deep expertise; repeat founder in space; lived the problem",
    weight: 12,
  },
  {
    section: "TEAM",
    criterion: "Time Since Launch",
    guidingQuestions: "How long since launch relative to the opportunity?",
    low: "> 24 months; limited momentum or stale narrative",
    medium: "12–24 months with steady learning",
    high: "< 12 months with sharp learning velocity and early momentum",
    weight: 8,
  },
  // PRODUCT Section (15% total)
  {
    section: "PRODUCT",
    criterion: "Product Maturity",
    guidingQuestions: "What's built and in use today?",
    low: "Idea/slides only",
    medium: "Prototype/MVP, limited usage",
    high: "Production-ready, active users, measurable outcomes",
    weight: 8,
  },
  {
    section: "PRODUCT",
    criterion: "Differentiation / Moat",
    guidingQuestions: "Is it unique vs. incumbents/new entrants? Can a moat form?",
    low: "Copycat, easily replicable",
    medium: "Some differentiation; time-limited edge",
    high: "Proprietary IP/data/approach; compounding moat",
    weight: 7,
  },
  // GTM Section (12% total)
  {
    section: "GTM",
    criterion: "Early Traction & Validation",
    guidingQuestions: "Any proof of demand beyond anecdotes?",
    low: "None; interviews only",
    medium: "Pilots/POCs/LOIs; growing waitlist",
    high: "Paying customers; strong retention & usage",
    weight: 7,
  },
  {
    section: "GTM",
    criterion: "Distribution Strategy",
    guidingQuestions: "Is there a clear, scalable GTM with efficient CAC and payback?",
    low: "No GTM plan; founder-led only",
    medium: "Early channels identified; CAC unproven",
    high: "Repeatable channels; improving CAC/payback; scalable partnerships",
    weight: 5,
  },
  // TECH Section (8% total)
  {
    section: "TECH",
    criterion: "Tech Readiness & Defensibility",
    guidingQuestions: "What's built? Is it scalable and defensible (IP/data)?",
    low: "Wireframes/slides; no infra",
    medium: "MVP on basic stack; limited robustness",
    high: "Proprietary IP/data; scalable, secure infra; clear roadmap",
    weight: 8,
  },
  // BUSINESS & DEAL Section (15% total)
  {
    section: "BUSINESS & DEAL",
    criterion: "High Margin Potential",
    guidingQuestions: "Does the model support strong gross margins and operating leverage?",
    low: "< 40% GM; services-heavy",
    medium: "40–60% GM; path unclear",
    high: "70%+ GM; software/data-like; strong unit economics",
    weight: 5,
  },
  {
    section: "BUSINESS & DEAL",
    criterion: "Fundability & Next Round Path",
    guidingQuestions: "Will next-round investors fund it given milestones?",
    low: "No clear path; milestones vague",
    medium: "Partial alignment with next-round bar",
    high: "Clear roadmap; Series A hooks and comparables",
    weight: 4,
  },
  {
    section: "BUSINESS & DEAL",
    criterion: "Exit / Return Potential",
    guidingQuestions: "Could this be 10x+ with multiple paths?",
    low: "< $100M ceiling",
    medium: "$100–500M potential",
    high: "$1B+ potential; multiple exit paths",
    weight: 3,
  },
  {
    section: "BUSINESS & DEAL",
    criterion: "Valuation / Terms",
    guidingQuestions: "Are entry terms attractive vs. peers/market?",
    low: "Overpriced (>3–4× peers)",
    medium: "Fair but stretched",
    high: "Attractive entry; good protections",
    weight: 1,
  },
  {
    section: "BUSINESS & DEAL",
    criterion: "X‑Factor / Thesis Alignment",
    guidingQuestions: "Does this fit our thesis and excite us?",
    low: "Outside thesis",
    medium: "Adjacent",
    high: "Perfect fit; strong conviction",
    weight: 1,
  },
  {
    section: "BUSINESS & DEAL",
    criterion: "Portfolio Fit / Cap Table",
    guidingQuestions: "Clean, accretive, founder/employee incentives healthy?",
    low: "Messy cap table; misaligned",
    medium: "Some complexity",
    high: "Clean; favorable ownership & governance",
    weight: 1,
  },
]
